/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTimetableRouteImport } from './routes/dashboard.timetable'
import { Route as DashboardTeachersRouteImport } from './routes/dashboard.teachers'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard.subjects'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardGeneratorRouteImport } from './routes/dashboard.generator'
import { Route as DashboardClassesRouteImport } from './routes/dashboard.classes'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimetableRoute = DashboardTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeneratorRoute = DashboardGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/timetable': typeof DashboardTimetableRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/timetable': typeof DashboardTimetableRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/dashboard/timetable': typeof DashboardTimetableRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/classes'
    | '/dashboard/generator'
    | '/dashboard/settings'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard/timetable'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/classes'
    | '/dashboard/generator'
    | '/dashboard/settings'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard/timetable'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/classes'
    | '/dashboard/generator'
    | '/dashboard/settings'
    | '/dashboard/subjects'
    | '/dashboard/teachers'
    | '/dashboard/timetable'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timetable': {
      id: '/dashboard/timetable'
      path: '/timetable'
      fullPath: '/dashboard/timetable'
      preLoaderRoute: typeof DashboardTimetableRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers': {
      id: '/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generator': {
      id: '/dashboard/generator'
      path: '/generator'
      fullPath: '/dashboard/generator'
      preLoaderRoute: typeof DashboardGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardClassesRoute: typeof DashboardClassesRoute
  DashboardGeneratorRoute: typeof DashboardGeneratorRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardTeachersRoute: typeof DashboardTeachersRoute
  DashboardTimetableRoute: typeof DashboardTimetableRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardGeneratorRoute: DashboardGeneratorRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardTimetableRoute: DashboardTimetableRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
